import js from "@eslint/js";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import { defineConfig, globalIgnores } from "eslint/config";
import tseslint from "typescript-eslint";

export default defineConfig([
	globalIgnores(["dist"]),
	reactHooks.configs.flat.recommended,
	reactRefresh.configs.vite,
	react.configs.flat.recommended,
	js.configs.recommended,
	{
		settings: {
			react: {
				version: "detect",
			},
		},
		rules: {
			"array-bracket-spacing": ["error", "never"],
			"array-element-newline": ["error", "consistent"],
			"arrow-body-style": ["error", "as-needed"],
			"arrow-parens": "error",
			"arrow-spacing": "error",
			"block-spacing": "error",
			"brace-style": ["error", "1tbs"],
			"comma-dangle": ["warn", "always-multiline"],
			"comma-spacing": ["error", { after: true, before: false }],
			"comma-style": ["error", "last"],
			"computed-property-spacing": "error",
			"curly": ["error", "all"],
			"default-case": "error",
			"dot-location": ["error", "property"],
			"eol-last": "error",
			"eqeqeq": "error",
			"func-names": "error",
			"func-style": ["error", "declaration"],
			"indent": ["error", "tab", { ignoredNodes: ["TemplateLiteral"], SwitchCase: 1 }],
			"linebreak-style": ["warn", "unix"],
			"lines-between-class-members": ["error", "always", { exceptAfterSingleLine: true }],
			"multiline-comment-style": ["error", "separate-lines"],
			"new-parens": "error",
			"no-alert": "warn",
			"no-array-constructor": "error",
			"no-await-in-loop": "error",
			"no-bitwise": "error",
			"no-confusing-arrow": "error",
			"no-console": "warn",
			"no-duplicate-imports": "warn",
			"no-else-return": "error",
			"no-empty": ["warn", { allowEmptyCatch: true }],
			"no-fallthrough": "error",
			"no-invalid-this": "error",
			"no-lonely-if": "error",
			"no-multi-spaces": "error",
			"no-multiple-empty-lines": "error",
			"no-restricted-imports": ["error", { patterns: ["./*", "../*", "!./*.module.css"] }],
			"no-self-compare": "error",
			"no-template-curly-in-string": "error",
			"no-trailing-spaces": "error",
			"no-undef-init": "error",
			"no-unreachable-loop": "error",
			"no-unused-expressions": "error",
			"no-unused-vars": ["warn", { args: "all", argsIgnorePattern: "^_", caughtErrors: "all", vars: "all" }],
			"no-useless-catch": "error",
			"no-useless-computed-key": "error",
			"no-useless-concat": "error",
			"no-useless-constructor": "error",
			"no-useless-rename": "error",
			"no-useless-return": "error",
			"no-whitespace-before-property": "error",
			"object-curly-newline": ["error", { consistent: true, multiline: true }],
			"object-curly-spacing": ["error", "always"],
			"object-property-newline": ["error", { allowAllPropertiesOnSameLine: true }],
			"one-var-declaration-per-line": "error",
			"operator-assignment": "error",
			"prefer-arrow-callback": "error",
			"prefer-const": "error",
			"prefer-destructuring": ["error", { AssignmentExpression: { array: false, object: false }, VariableDeclarator: { array: false, object: true } }],
			"prefer-object-spread": "error",
			"prefer-spread": "error",
			"prefer-template": "error",
			"quotes": ["error", "double", { avoidEscape: true }],
			"radix": ["error", "as-needed"],
			"react-hooks/exhaustive-deps": ["error"],
			"react-hooks/rules-of-hooks": "error",
			"react/boolean-prop-naming": "error",
			"react/function-component-definition": "error",
			"react/jsx-boolean-value": "error",
			"react/jsx-child-element-spacing": "error",
			"react/jsx-closing-bracket-location": "error",
			"react/jsx-curly-brace-presence": "error",
			"react/jsx-equals-spacing": ["error", "never"],
			"react/jsx-filename-extension": ["error", { extensions: [".jsx", ".tsx"] }],
			"react/jsx-no-useless-fragment": "error",
			"react/jsx-pascal-case": "error",
			"react/jsx-props-no-multi-spaces": "error",
			"react/jsx-sort-props": "warn",
			"react/jsx-tag-spacing": "error",
			"react/no-access-state-in-setstate": "error",
			"react/no-adjacent-inline-elements": "error",
			"react/no-danger": "warn",
			"react/no-did-mount-set-state": "error",
			"react/no-did-update-set-state": "error",
			"react/no-this-in-sfc": "error",
			"react/no-typos": "error",
			"react/no-unsafe": "error",
			"react/prefer-stateless-function": "error",
			"react/react-in-jsx-scope": "off",
			"react/sort-comp": "warn",
			"react/sort-default-props": "warn",
			"react/sort-prop-types": "warn",
			"require-await": "error",
			"semi-spacing": "error",
			"semi": ["error", "always"],
			"sort-imports": ["warn", { ignoreCase: true, ignoreDeclarationSort: true }],
			"space-before-blocks": "error",
			"space-before-function-paren": ["error", { anonymous: "never", asyncArrow: "always", named: "never" }],
			"space-in-parens": "error",
			"space-infix-ops": "error",
			"spaced-comment": ["error", "always", { markers: ["/"] }],
			"switch-colon-spacing": "error",
			"template-curly-spacing": "error",
			"template-tag-spacing": ["error", "never"],
			"wrap-regex": "error",
		},
	},
	{
		files: ["**/*.ts", "**/*.tsx"],
		extends: [tseslint.configs.recommendedTypeChecked, tseslint.configs.strictTypeChecked, tseslint.configs.stylisticTypeChecked],
		languageOptions: {
			parserOptions: {
				project: "tsconfig.json",
				warnOnUnsupportedTypeScriptVersion: false,
			},
		},
		rules: {
			"@typescript-eslint/array-type": ["error", { default: "array-simple" }],
			"@typescript-eslint/ban-ts-comment": "warn",
			"@typescript-eslint/class-literal-property-style": "error",
			"@typescript-eslint/consistent-indexed-object-style": ["error", "record"],
			"@typescript-eslint/consistent-type-assertions": "error",
			"@typescript-eslint/consistent-type-definitions": ["error", "interface"],
			"@typescript-eslint/consistent-type-imports": ["error", { prefer: "type-imports", disallowTypeAnnotations: false, fixStyle: "inline-type-imports" }],
			"@typescript-eslint/explicit-member-accessibility": "error",
			"@typescript-eslint/method-signature-style": "error",
			"@typescript-eslint/no-array-constructor": "error",
			"@typescript-eslint/no-confusing-non-null-assertion": "error",
			"@typescript-eslint/no-explicit-any": "error",
			"@typescript-eslint/no-misused-promises": ["error", { checksVoidReturn: false }],
			"@typescript-eslint/no-unnecessary-boolean-literal-compare": "error",
			"@typescript-eslint/no-unused-expressions": "error",
			"@typescript-eslint/no-unused-vars": ["warn", { args: "all", argsIgnorePattern: "^_", caughtErrors: "all", vars: "all" }],
			"@typescript-eslint/no-useless-constructor": "error",
			"@typescript-eslint/prefer-for-of": "error",
			"@typescript-eslint/prefer-includes": "error",
			"@typescript-eslint/prefer-readonly": "error",
			"@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
		},
	},
]);
